$(document).ready(function(){
	$("#login_form").validate({
		rules:{
			username:{
				required:true,
			},
			password:{
				required:true,
				minlength:6,
				maxlength:16
			}
		},
		messages:{
			username:{
				required:"姓名不能为空"
			},
			password:{
				required:"密码不能为空",
				minlength:"密码长度不合法",
				maxlength:"密码长度不合法"
			}
		}
	});
	$("#btn_reset").click(function(){
		this.reset();
	});
	$("#btn_login").click(function(){
		$.ajax({
			type:"POST",
			url:"login",
			data:{
				username:$("#username").val(),
				password:$("#password").val()
			},
			success:function(data){
				
				if(data=="success"){
					window.location.href="index.html";
				}else{
					window.location.href="Login.html";
				}
			},
			error:function(jqXHR){
				$("#login_msg").html(jqXHR.state);
			}
		});
	});
});